### ISSUE TITLE
I wish to contribute!

### ISSUE THREAD

**Issue by sunmughan** [TheWCKD/CoronaVirus-Outbreak-App#11]
Hey, first of all a big thanks to you for developing this project. Your project is exactly what we need in India. If you allow, i can contribute and add several necessary features in the app like :

- Latest News/Posts on Corona
- Diagnose Submission/Request
- Helplines (All Local + International)
- One click mail to central government registered departments for corona treatments.
- Suspiscious Patient information submit with images/videos and texts.
- Health Advisory
- Local police/hospitals and medical listings with one click contacts.
- Become a Volunteer (special feature for people who want to contribute us by providing updates and new patient information with us)

I will be waiting for your reply :)

**Comment by TheWCKD** [comment]
> Hey, first of all a big thanks to you for developing this project. Your project is exactly what we need in India. If you allow, i can contribute and add several necessary features in the app like :
> 
> * Latest News/Posts on Corona
> * Diagnose Submission/Request
> * Helplines (All Local + International)
> * One click mail to central government registered departments for corona treatments.
> * Suspiscious Patient information submit with images/videos and texts.
> * Health Advisory
> * Local police/hospitals and medical listings with one click contacts.
> * Become a Volunteer (special feature for people who want to contribute us by providing updates and new patient information with us)
> 
> I will be waiting for your reply :)

Hello, 

Unfortunately, the only way you can contribute to the project is by sharing it or the app.

Thanks.
