### ISSUE TITLE
UK recovery stats not working since 1.5.1

### ISSUE THREAD

**Issue by steve51184** [TheWCKD/CoronaVirus-Outbreak-App#13]
Appreciate the fix you just put out for 1.5.3 love this app so Ty for your work! There's still a bug since v1.5.1/2 that isn't showing the UK recovery stats.. image included..

![Screenshot_20200405-010026](https://user-images.githubusercontent.com/12534098/78463804-24774b00-76d9-11ea-88a0-a68cdb74ffc4.jpg)

**Comment by TheWCKD** [comment]
Will be fixed in 1.6.0. It's not related to the app, it's related to the data source.
