### ISSUE TITLE
Rate calculations

### ISSUE THREAD

**Issue by ccgreen** [TheWCKD/CoronaVirus-Outbreak-App#9]
The recovery rate and death rate - on the front page of the app - seem to be calculated using the active cases, not the total cases. I believe this to be an error as if someone is an active case I'd like to assume they have neither recovered nor died.

Due to the active cases being smaller than the total cases, this causes both rates to be higher than they should be.

**Comment by ccgreen** [comment]
This could just be me misunderstanding what the rate means however

**Comment by TheWCKD** [comment]
Fixed in >= 1.3.0, thanks!
